### ISSUE TITLE
LSH Implementation

### ISSUE THREAD

**Issue by pedroalbanese** [RyuaNerin/go-krypto#1]
Greetings!

I'm trying to implement LSH hashsum, but is going wrong. 

<pre>
package main
import (
	"encoding/hex"
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/RyuaNerin/go-krypto/lsh256"
)

func main() {
	flag.Parse()
	h := lsh256.New()
	if _, err := io.Copy(h, os.Stdin); err != nil {
		panic(err)
	}
	fmt.Println(hex.EncodeToString(h.Sum(nil)))
}</pre>

I'm getting the following error:

<pre>
$ go build -ldflags=-s .
# github.com/RyuaNerin/go-krypto/lsh256
C:\Users\0wner\go\src\github.com\RyuaNerin\go-krypto\lsh256\lsh256.go:134:38: invalid operation: 255 >> rbits (shift count type int, must be unsigned integer)
C:\Users\0wner\go\src\github.com\RyuaNerin\go-krypto\lsh256\lsh256.go:152:31: invalid operation: 1 << (7 - rbits) (shift count type int, must be unsigned integer)
C:\Users\0wner\go\src\github.com\RyuaNerin\go-krypto\lsh256\lsh256.go:178:31: invalid operation: temp[i >> 2] >> (i << 3 & 31) (shift count type int, must be unsigned integer)
C:\Users\0wner\go\src\github.com\RyuaNerin\go-krypto\lsh256\lsh256.go:182:26: invalid operation: 255 << (8 - rbits) (shift count type int, must be unsigned integer)
C:\Users\0wner\go\src\github.com\RyuaNerin\go-krypto\lsh256\lsh256.go:265:9: invalid operation: value << rot (shift count type int, must be unsigned integer)
C:\Users\0wner\go\src\github.com\RyuaNerin\go-krypto\lsh256\lsh256.go:265:26: invalid operation: value >> (32 - rot) (shift count type int, must be unsigned integer)</pre>

How to proceed? Thanks in advance.

**Comment by RyuaNerin** [comment]
hello pedroalbanese!
I first wrote it, i used go 1.14. it seems that the syntax rule has changed in the meantime.
I think it will be not possible to check quickly, because it's a college exam period.
So I'll check as soon as I finish my busy work.

**Comment by pedroalbanese** [comment]
Now I get it. I was trying to compile with Go 1.13.1, now it works fine except HMAC. When I try to compute the HMAC of a file with more than 20kb it bugs:

<pre>
package main
import (
	"encoding/hex"
	"flag"
	"fmt"
	"io"
	"os"
	"log"
	"crypto/hmac"
	"github.com/RyuaNerin/go-krypto/lsh256"
)

        var key = flag.String("key", "", "Secret Key.")
        
func main() {
    flag.Parse()
	var keyHex string
	keyHex = *key
	key, err := hex.DecodeString(keyHex)
	if err != nil {
                log.Fatal(err)
	}
	h := hmac.New(lsh256.New, key)
	if _, err = io.Copy(h, os.Stdin); err != nil {
                log.Fatal(err)
	}
	fmt.Println(hex.EncodeToString(h.Sum(nil)))
        os.Exit(0)
}
</pre>

I'm get the following error:
<pre>
$ ./hmac < 22kbfile.ext
panic: runtime error: slice bounds out of range [:-2726]

goroutine 1 [running]:
github.com/RyuaNerin/go-krypto/lsh256.(*lsh256).Write(0x118b4800, 0x118b8000, 0x5931, 0x8000, 0x4b59c0, 0x0, 0x118b8000)
        C:/Users/0wner/go/src/github.com/RyuaNerin/go-krypto/lsh256/lsh256.go:111 +0x307
crypto/hmac.(*hmac).Write(0x11880090, 0x118b8000, 0x5931, 0x8000, 0x5931, 0x0, 0x0)
        c:/go/src/crypto/hmac/hmac.go:72 +0x3f
io.copyBuffer(0x1318090, 0x11880090, 0x4e9030, 0x118840d0, 0x118b8000, 0x8000, 0x8000, 0x0, 0x0, 0x11882030, ...)
        c:/go/src/io/io.go:411 +0x190
io.Copy(...)
        c:/go/src/io/io.go:368
main.main()
        H:/PGMM/lshsum/lsh/hmac/hmac/main.go:25 +0x189
</pre>

Thanks.

**Comment by pedroalbanese** [comment]
Your libraries are fantastic! Congrats. Don't be discouraged. It is a great honor to be able to use KISA's algorithms (we have little news of this here in the west). Don't be in a hurry, but let me know when you can see this.

Thank You once again!

**Comment by RyuaNerin** [comment]
Fixed some incorrect implementations. Now, the library are expected to operate normaly, ported from Java source code provides by KISA.

**Comment by pedroalbanese** [comment]
Thank You!!

**Comment by pedroalbanese** [comment]
Greetings!! (I didn't want to open a new issue)

I was wondering if it would be possible to implement HAS-160 and EC-KCDSA, what do you say? I would like to make a tool comparable to my other GOSTTk and GMSMTk (https://github.com/pedroalbanese/gmsmtk) tools, I thought of a KISATk call. I mean, a cryptosystem independent of western algorithms...

Thanks!

**Comment by RyuaNerin** [comment]
Hello, dear @pedroalbanese

I didn't have checked github these days, i'm sorry for late reply

Implementing HAS-160, EC-KCDSA seems like a good idea.
When i have time, I will try porting to golang. but i have some of work to do, so don't get your hopes up.

Thanks
