### ISSUE TITLE
Fix incorrect implementation

### ISSUE THREAD

**Issue by RyuaNerin** [RyuaNerin/go-krypto#2]
- [x] ARIA
- [x] HIGHT
- [x] LEA
- [x] LSH256
- [x] LSH512
- [x] SEED

**Comment by cedws** [comment]
Did you use any test vectors for the implementation of SEED? I'm getting an unexpected result but maybe I just have the wrong key. Don't worry, not using it for any serious project. 😄

**Comment by cedws** [comment]
Oh, you have tests. No worries it's just me then. Cheers.

**Comment by RyuaNerin** [comment]
There're reports that some algorithms is wrong, so need to check this. Sorry for the inconvenience.

**Comment by cedws** [comment]
SEED is decrypting as expected now. Thank you!
