### ISSUE TITLE
PEM support for EC-KCDSA keys

### ISSUE THREAD

**Issue by pedroalbanese** [RyuaNerin/go-krypto#4]
Greetings!

Firstly I would like to say that the eckcdsa library does not work on my PC, just making these changes in the util.go file, perhaps because my PC is 32-bit:

```go
func Bytes(bits int) int {
	return int((uint(bits) + 7) & ^uint(0xFFFFFFF8) / 8)
}
```

But the problem is I can't save the keys in hex, I don't understand how to serialize the keys without losing their structure.

Would it be possible, please, to implement PEM support or Serialize/Deserialize function for EC-KCDSA keys?

Thanks in advance.

**Comment by RyuaNerin** [comment]
Hello. I'll check EC-KCDSA official document.

**Comment by pedroalbanese** [comment]
@RyuaNerin 

Thank You very much!
